/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import static com.app.interfaz.Inicio_sesion.cox;
import com.app.manejodatos.Grafo;
import java.awt.BorderLayout;

/**
 *
 * @author ADMIN
 */
public class ADMIN extends javax.swing.JFrame {
    
    Grafo grafo;
    Drawer draw;
    Boolean perm;

    /**
     * Creates new form ADMIN
     */
    public ADMIN(Grafo grafoload) {
        grafo = grafoload;
        this.setExtendedState(this.MAXIMIZED_BOTH);
        initComponents();      
        draw = new Drawer(perm,cox,null,grafo.getNodos(),grafo.getAristas());
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(draw,BorderLayout.CENTER);
        jPanel5.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoN4 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bienvenida1 = new javax.swing.JLabel();
        Bienvenida2 = new javax.swing.JLabel();
        Buscar2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Buscar3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 190, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        LogoN4.setText(bundle.getString("crear_cuenta.LogoN4.text")); // NOI18N
        jPanel1.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 660, 90));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN3.setText(bundle.getString("Inicio_sesion.LogoN3.text")); // NOI18N
        jPanel1.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 340, 80));

        Bienvenida.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida.setText("Aristas");
        jPanel1.add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        Buscar1.setBackground(new java.awt.Color(140, 0, 0));
        Buscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliminar");
        Buscar1.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 170, 70));

        Bienvenida1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida1.setText("¡Bienvenido(a)!");
        jPanel1.add(Bienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        Bienvenida2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida2.setText("Nodos");
        jPanel1.add(Bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Buscar2.setBackground(new java.awt.Color(140, 0, 0));
        Buscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Agregarnodo(evt);
            }
        });
        Buscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popup(evt);
            }
        });
        Buscar2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar ");
        Buscar2.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 170, 70));

        Buscar3.setBackground(new java.awt.Color(140, 0, 0));
        Buscar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar ");
        Buscar3.add(jLabel4, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 170, 70));

        Buscar.setBackground(new java.awt.Color(140, 0, 0));
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");
        Buscar.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 170, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 1080));

        jPanel2.setBackground(new java.awt.Color(140, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setEnabled(false);
        jPanel5.setFocusable(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 830, 900));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, -10, 1160, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregarnodo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregarnodo
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregarnodo

    private void popup(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popup
        // TODO add your handling code here:
    }//GEN-LAST:event_popup

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JLabel Bienvenida1;
    private javax.swing.JLabel Bienvenida2;
    private javax.swing.JPanel Buscar;
    private javax.swing.JPanel Buscar1;
    private javax.swing.JPanel Buscar2;
    private javax.swing.JPanel Buscar3;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
