/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

/**
 *
 * @author ADMIN
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoN4 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Buscar1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bienvenida1 = new javax.swing.JLabel();
        Bienvenida2 = new javax.swing.JLabel();
        Buscar2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Buscar3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 190, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        LogoN4.setText(bundle.getString("crear_cuenta.LogoN4.text")); // NOI18N
        jPanel1.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 660, 90));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN3.setText(bundle.getString("Inicio_sesion.LogoN3.text")); // NOI18N
        jPanel1.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 340, 80));

        Bienvenida.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida.setText("Aristas");
        jPanel1.add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        Buscar.setBackground(new java.awt.Color(140, 0, 0));
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarMousePressed(evt);
            }
        });
        Buscar.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");
        Buscar.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 170, 70));

        Buscar1.setBackground(new java.awt.Color(140, 0, 0));
        Buscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buscar1MousePressed(evt);
            }
        });
        Buscar1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliminar");
        Buscar1.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 170, 70));

        Bienvenida1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida1.setText("¡Bienvenido(a)!");
        jPanel1.add(Bienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        Bienvenida2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida2.setText("Nodos");
        jPanel1.add(Bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Buscar2.setBackground(new java.awt.Color(140, 0, 0));
        Buscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buscar2MousePressed(evt);
            }
        });
        Buscar2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar ");
        Buscar2.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 170, 70));

        Buscar3.setBackground(new java.awt.Color(140, 0, 0));
        Buscar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buscar3MousePressed(evt);
            }
        });
        Buscar3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar ");
        Buscar3.add(jLabel4, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 170, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMousePressed
        Camino.setText("");
        String nodoINI = "";
        String nodoFIN = "";
        nodoINI = (String) NodoA.getSelectedItem();
        nodoFIN = (String) NodoB.getSelectedItem();
        Boolean iniesp = false;
        Boolean finesp = false;
        String temp3 = "";
        String temp4 = "";
        if(NodoA.getSelectedItem().equals("Biblioteca")){
            nodoINI = "J";
            iniesp = true;
            temp3 = "Biblioteca->";
        }
        if(NodoB.getSelectedItem().equals("Biblioteca")){
            nodoFIN = "J";
            finesp = true;
            temp4 = "Biblioteca";
        }
        if(NodoA.getSelectedItem().equals("Auditorio menor")){
            nodoINI = "J";
            iniesp = true;
            temp3 = "Auditorio menor->";
        }
        if(NodoB.getSelectedItem().equals("Auditorio menor")){
            nodoFIN = "J";
            finesp = true;
            temp4 = "Auditorio menor";
        }
        if(NodoA.getSelectedItem().equals("Auditorio mayor")){
            nodoINI = "H";
            iniesp = true;
            temp3 = "Auditorio mayor->";
        }
        if(NodoB.getSelectedItem().equals("Auditorio mayor")){
            nodoFIN = "H";
            finesp = true;
            temp4 = "Auditorio mayor";
        }
        if(nodoINI == nodoFIN){
            temp3 = "";
        }
        ListaEnlazada camino = grafo.Dijkstra(nodoINI, nodoFIN, check,Camino);
        draw.setCamino(camino);
        draw.ponerCamino();
        if(iniesp && !finesp){
            Nodo temp = camino.getCabeza().getSiguiente();

            while(temp != null){
                if(Camino.getText().contains("Se encuentra sobre el mismo nodo")){
                    Camino.setText("Se encuentra sobre el mismo nodo");
                    break;
                }
                temp3 = temp3 + temp.getNombre();

                temp = temp.getSiguiente();
                if(temp != null){
                    temp3 = temp3 + "->";
                }
            }
        }
        if(finesp && !iniesp){
            Nodo temp = camino.getCabeza();
            while(temp.getSiguiente() != null){
                if(Camino.getText().contains("Se encuentra sobre el mismo nodo")){
                    Camino.setText("Se encuentra sobre el mismo nodo");
                    break;
                }
                temp3 = temp3 + temp.getNombre();
                temp = temp.getSiguiente();
                if(temp != null){
                    temp3 = temp3 + "->";
                }
                if(temp.getSiguiente() == null){
                    temp3 = temp3 + temp4;
                    break;
                }
            }
        }
        if(!iniesp && !finesp){
            Nodo temp = camino.getCabeza();

            while(temp != null){
                if(Camino.getText().contains("Se encuentra sobre el mismo nodo")){
                    Camino.setText("Se encuentra sobre el mismo nodo");
                    break;
                }
                temp3 = temp3 + temp.getNombre();

                temp = temp.getSiguiente();
                if(temp != null){
                    temp3 = temp3 + "->";
                }
            }
        }
        if(iniesp && finesp){
            Nodo temp = camino.getCabeza().getSiguiente();
            while(temp.getSiguiente() != null){
                if(Camino.getText().contains("Se encuentra sobre el mismo nodo")){
                    Camino.setText("Se encuentra sobre el mismo nodo");
                    break;
                }
                temp3 = temp3 + temp.getNombre();
                temp = temp.getSiguiente();
                if(temp != null){
                    temp3 = temp3 + "->";
                }
                if(temp.getSiguiente() == null){
                    temp3 = temp3 + temp4;
                    break;
                }
            }
        }
        if(camino.getSize() > 0){
            Camino.append(temp3);
        }

    }//GEN-LAST:event_BuscarMousePressed

    private void Buscar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar1MousePressed

    private void Buscar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar2MousePressed

    private void Buscar3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JLabel Bienvenida1;
    private javax.swing.JLabel Bienvenida2;
    private javax.swing.JPanel Buscar;
    private javax.swing.JPanel Buscar1;
    private javax.swing.JPanel Buscar2;
    private javax.swing.JPanel Buscar3;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
