/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import com.app.manejodatos.Grafo;
import com.app.manejodatos.Nodo;
import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class AgregarNodos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarNodos
     */
    public AgregarNodos() {
        initComponents();
        Nombrevacio.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeparadorUser3 = new javax.swing.JPanel();
        SeparadorUser4 = new javax.swing.JPanel();
        SeparadorUser5 = new javax.swing.JPanel();
        SeparadorUser6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LogoN4 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        Buscar4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Bienvenida2 = new javax.swing.JLabel();
        Y = new javax.swing.JLabel();
        SeparadorUser1 = new javax.swing.JPanel();
        SeparadorUser7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nnodo = new javax.swing.JTextField();
        PosicionX = new javax.swing.JTextField();
        PosicionY = new javax.swing.JTextField();
        Nombrevacio = new javax.swing.JLabel();

        SeparadorUser3.setBackground(new java.awt.Color(0, 0, 0));

        SeparadorUser4.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorUser3.add(SeparadorUser4);

        SeparadorUser5.setBackground(new java.awt.Color(0, 0, 0));

        SeparadorUser6.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorUser5.add(SeparadorUser6);

        SeparadorUser3.add(SeparadorUser5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 190, 15));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        LogoN4.setText(bundle.getString("crear_cuenta.LogoN4.text")); // NOI18N
        jPanel1.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 660, 90));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN3.setText(bundle.getString("Inicio_sesion.LogoN3.text")); // NOI18N
        jPanel1.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 340, 80));

        X.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        X.setText("Y");
        jPanel1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, 30));

        Buscar4.setBackground(new java.awt.Color(140, 0, 0));
        Buscar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agergar_Nodo(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Agergar_Nodo(evt);
            }
        });
        Buscar4.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar ");
        Buscar4.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 750, 170, 70));

        Bienvenida2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida2.setText("¡Bienvenido(a)!");
        jPanel1.add(Bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        Y.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        Y.setText("X");
        jPanel1.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, 30));

        SeparadorUser1.setBackground(new java.awt.Color(0, 0, 0));

        SeparadorUser7.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorUser1.add(SeparadorUser7);

        jPanel1.add(SeparadorUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 500, 1));

        jPanel2.setBackground(new java.awt.Color(140, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, -20, 1220, 1100));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel8.setText(bundle.getString("crear_cuenta.jLabel3.text")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese la Posicion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 510, 50));

        Nnodo.setBackground(new java.awt.Color(255, 190, 15));
        Nnodo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Nnodo.setForeground(java.awt.Color.gray);
        Nnodo.setText("Ingrese el nombre del nodo");
        Nnodo.setBorder(null);
        Nnodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Limpiar(evt);
            }
        });
        Nnodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NnodoActionPerformed(evt);
            }
        });
        jPanel1.add(Nnodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 500, 40));

        PosicionX.setBackground(new java.awt.Color(255, 190, 15));
        PosicionX.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PosicionX.setForeground(java.awt.Color.gray);
        PosicionX.setText("Ingrese la posicion del Nodo");
        PosicionX.setBorder(null);
        PosicionX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PosicionXMousePressed(evt);
            }
        });
        jPanel1.add(PosicionX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 330, 30));

        PosicionY.setBackground(new java.awt.Color(255, 190, 15));
        PosicionY.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PosicionY.setForeground(java.awt.Color.gray);
        PosicionY.setText("Ingrese la posicion del Nodo");
        PosicionY.setBorder(null);
        PosicionY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PosicionYMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PosicionYMousePressed(evt);
            }
        });
        PosicionY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosicionYActionPerformed(evt);
            }
        });
        jPanel1.add(PosicionY, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, 30));

        Nombrevacio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombrevacio.setForeground(new java.awt.Color(204, 0, 0));
        Nombrevacio.setText("El nombre del nodo no puede estar vacio");
        jPanel1.add(Nombrevacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 830, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agergar_Nodo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agergar_Nodo
        String nombreNodo = Nnodo.getText();
        if (nombreNodo == null || Nnodo.getText().equals("")) {
            Nombrevacio.setVisible(true);
            
            return;
        }
        Nodo nodoNuevo = new Nodo(nombreNodo);
        grafo.agregarNodo(nodoNuevo);
       
       
    }//GEN-LAST:event_Agergar_Nodo

    private void NnodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NnodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NnodoActionPerformed

    private void Limpiar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Limpiar
        Nnodo.setText("");
         Nnodo.setForeground(Color.black);

    }//GEN-LAST:event_Limpiar

    private void PosicionYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosicionYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosicionYActionPerformed

    private void PosicionXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicionXMousePressed
        PosicionX.setText("");
        PosicionX.setForeground(Color.black);
    }//GEN-LAST:event_PosicionXMousePressed

    private void PosicionYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicionYMousePressed
        PosicionY.setText("");
        PosicionY.setForeground(Color.black);
    }//GEN-LAST:event_PosicionYMousePressed

    private void PosicionYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PosicionYMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PosicionYMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarNodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarNodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarNodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarNodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarNodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida2;
    private javax.swing.JPanel Buscar4;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private javax.swing.JTextField Nnodo;
    private javax.swing.JLabel Nombrevacio;
    private javax.swing.JTextField PosicionX;
    private javax.swing.JTextField PosicionY;
    private javax.swing.JPanel SeparadorUser1;
    private javax.swing.JPanel SeparadorUser3;
    private javax.swing.JPanel SeparadorUser4;
    private javax.swing.JPanel SeparadorUser5;
    private javax.swing.JPanel SeparadorUser6;
    private javax.swing.JPanel SeparadorUser7;
    private javax.swing.JLabel X;
    private javax.swing.JLabel Y;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
