/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import com.app.utilidad.PanelRound;
import com.app.conexion.Conexion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import com.app.manejodatos.Grafo;
import java.awt.BorderLayout;
import java.util.Arrays;
import javax.swing.JFrame;
import raven.toast.Notifications;

/**
 *
 * @author bohor
 */
public class crear_cuenta extends javax.swing.JFrame {
    
    int indice = 0;
    Boolean[] ver = new Boolean[2];
    Conexion cox = null;
    Grafo grafo = null;
    

    /**
     * Creates new form Inicio_sesion
     */
    public crear_cuenta(Conexion coxload,Grafo Grafoload) {
        cox = coxload;
        grafo = Grafoload;
        Arrays.fill(ver, false);
        initComponents();
        PanelRound dgree1 = new PanelRound();
        PanelRound dgree2 = new PanelRound();
        InicioSesion.setLayout(new BorderLayout());
        InicioSesion.add(dgree1,BorderLayout.CENTER);
        InicioSesion.setOpaque(true);

        CrearCuenta.setLayout(new BorderLayout());
        CrearCuenta.add(dgree2,BorderLayout.CENTER);
        CrearCuenta.setOpaque(true);
        carrusel();
        this.dispose();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.getRootPane().requestFocusInWindow();
        User1.setCaretPosition(User1.getText().length());
        User1.moveCaretPosition(User1.getText().length()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Fondo1 = new javax.swing.JPanel();
        Password2Text = new javax.swing.JLabel();
        Password2 = new javax.swing.JPasswordField();
        Password1Text = new javax.swing.JLabel();
        Password1 = new javax.swing.JPasswordField();
        User1 = new javax.swing.JTextField();
        IniciarSesionTexto1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SeparadorUser = new javax.swing.JPanel();
        SeparadorPass4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InicioSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SeparadorPass = new javax.swing.JPanel();
        CrearCuenta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        Password1See = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Password2See = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JPanel();
        Carrusel = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("crear_cuenta.jMenu1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 60, 67));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password2Text.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password2Text.setForeground(new java.awt.Color(140, 140, 140));
        Password2Text.setText(bundle.getString("crear_cuenta.Password2Text.text")); // NOI18N
        Password2Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Password2Text.setDoubleBuffered(true);
        Fondo1.add(Password2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, -1, -1));

        Password2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password2.setForeground(new java.awt.Color(140, 140, 140));
        Password2.setText(bundle.getString("crear_cuenta.Password2.text")); // NOI18N
        Password2.setBorder(null);
        Password2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password2MousePressed(evt);
            }
        });
        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });
        Fondo1.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 460, 40));

        Password1Text.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password1Text.setForeground(new java.awt.Color(140, 140, 140));
        Password1Text.setText(bundle.getString("crear_cuenta.Password1Text.text")); // NOI18N
        Password1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Password1Text.setDoubleBuffered(true);
        Fondo1.add(Password1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        Password1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password1.setForeground(new java.awt.Color(140, 140, 140));
        Password1.setText(bundle.getString("crear_cuenta.Password1.text")); // NOI18N
        Password1.setBorder(null);
        Password1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password1MousePressed(evt);
            }
        });
        Fondo1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 470, 40));

        User1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        User1.setForeground(java.awt.Color.gray);
        User1.setText(bundle.getString("crear_cuenta.User1.text")); // NOI18N
        User1.setToolTipText(bundle.getString("crear_cuenta.User1.toolTipText")); // NOI18N
        User1.setBorder(null);
        User1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User1MousePressed(evt);
            }
        });
        User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User1ActionPerformed(evt);
            }
        });
        Fondo1.add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 500, 30));

        IniciarSesionTexto1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 48)); // NOI18N
        IniciarSesionTexto1.setText(bundle.getString("crear_cuenta.IniciarSesionTexto1.text")); // NOI18N
        Fondo1.add(IniciarSesionTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 270, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel7.setText(bundle.getString("crear_cuenta.jLabel7.text")); // NOI18N
        Fondo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        SeparadorUser.setBackground(new java.awt.Color(0, 0, 0));
        Fondo1.add(SeparadorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 500, 1));

        SeparadorPass4.setBackground(new java.awt.Color(0, 0, 0));
        Fondo1.add(SeparadorPass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 505, 1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel2.setText(bundle.getString("crear_cuenta.jLabel2.text")); // NOI18N
        Fondo1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        InicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        InicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        InicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InicioSesion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioSesionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InicioSesionMousePressed(evt);
            }
        });
        InicioSesion.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(bundle.getString("crear_cuenta.jLabel1.text")); // NOI18N
        InicioSesion.add(jLabel1, new java.awt.GridBagConstraints());

        Fondo1.add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 750, 160, 70));

        SeparadorPass.setBackground(new java.awt.Color(0, 0, 0));
        Fondo1.add(SeparadorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 500, 1));

        CrearCuenta.setBackground(new java.awt.Color(255, 255, 255));
        CrearCuenta.setForeground(new java.awt.Color(140, 0, 0));
        CrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearCuentaMousePressed(evt);
            }
        });
        CrearCuenta.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(bundle.getString("crear_cuenta.jLabel6.text")); // NOI18N
        CrearCuenta.add(jLabel6, new java.awt.GridBagConstraints());

        Fondo1.add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 160, 70));

        Mensaje.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Mensaje.setForeground(new java.awt.Color(204, 255, 204));
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Mensaje.setText(bundle.getString("crear_cuenta.dwdawdad.text")); // NOI18N
        Mensaje.setName("dwdawdad"); // NOI18N
        Fondo1.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 830, 670, 20));
        Mensaje.getAccessibleContext().setAccessibleName(bundle.getString("crear_cuenta.dwdawdad.AccessibleContext.accessibleName")); // NOI18N

        Password1See.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/Noeye-removebg-preview.png"))); // NOI18N
        Password1See.setText(bundle.getString("crear_cuenta.Password1See.text")); // NOI18N
        Password1See.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Password1See.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password1SeeMousePressed(evt);
            }
        });
        Fondo1.add(Password1See, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(140, 140, 140));
        jLabel9.setText(bundle.getString("crear_cuenta.jLabel9.text")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabel9.setDoubleBuffered(true);
        Fondo1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        Password2See.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/Noeye-removebg-preview.png"))); // NOI18N
        Password2See.setText(bundle.getString("crear_cuenta.Password2See.text")); // NOI18N
        Password2See.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Password2See.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password2SeeMousePressed(evt);
            }
        });
        Fondo1.add(Password2See, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/upblogo.jpg"))); // NOI18N
        jLabel10.setText(bundle.getString("crear_cuenta.jLabel10.text")); // NOI18N
        Fondo1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 220));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel4.setText(bundle.getString("crear_cuenta.jLabel4.text")); // NOI18N
        Fondo1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 1080));

        Fondo2.setBackground(new java.awt.Color(0, 0, 0));
        Fondo2.setForeground(new java.awt.Color(0, 60, 67));
        Fondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Fondo2.add(Carrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 830, 930));

        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioSesionMouseClicked

    private void User1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User1MousePressed
        if(Password2.getText().equals("")){
                Password2Text.setText("Ingrese nuevamente su contraseña");
        }
        if(Password1.getText().equals("")){
                Password1Text.setText("Ingrese su contraseña");
        }
        if(!User1.getText().equals("Ingrese su nombre de usuario")){
            return;
        }
        else{
            User1.setText("");
            User1.setForeground(Color.black);
        }
        

    }//GEN-LAST:event_User1MousePressed

    private void InicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioSesionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioSesionMouseEntered

    private void CrearCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCuentaMousePressed
        
        if(User1.getText().contains(" ")){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"El usuario no puede tener espacios"); 
            return;
        }
        if(User1.getText().equals("") || User1.getText().equals("Ingrese el nombre de usuario")){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"Ingrese un nombre de usuario");
            return;
        }
        if(Password1.getText().equals("")){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"Ingrese la contraseña");
            return;
        }
        if(Password2.getText().equals("")){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"Ingrese nuevamente la contraseña");
            return;
        }
        if(!Password1.getText().equals(Password2.getText())){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"Contraseñas no coinciden");
            return;
        }
        if(Password1.getText().length() < 8){
            Notifications.getInstance().show(Notifications.Type.INFO,Notifications.Location.TOP_CENTER,"La contraseña debe tener al menos 8 caracteres");
            return;
        }
        if(Password1.getText().length() > 32){
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.TOP_CENTER,"La contraseña puede tener maximo 32 caracteres");
            return;
        }
        if ((Password1.getText().matches(".*[A-Z].*") && Password1.getText().matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]{2,}.*") && !Password1.getText().contains(" "))){
            Boolean veri = cox.addTotableUsers(User1.getText(), Password1.getText());
            if(veri == true){
                Notifications.getInstance().show(Notifications.Type.SUCCESS,Notifications.Location.TOP_CENTER,"El usuario ha sido creado");
                return;
            }
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.TOP_CENTER,"El usuario ya existe");
            
        }
        else{
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.TOP_CENTER,"La contraseña no puede tener espacios, debe tener al menos 2 caracteres espaciales y 1 mayuscula");
            return;
        }
        if((!Password1.getText().matches(".*[A-Z].*") && !Password1.getText().matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]{2,}.*") && Password1.getText().contains(" "))){
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.TOP_CENTER,"La contraseña no puede tener espacios, debe tener al menos 2 caracteres espaciales y 1 mayuscula");
        }
        
        
    }//GEN-LAST:event_CrearCuentaMousePressed

    private void User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User1ActionPerformed

    private void Password1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password1MousePressed

        if(User1.getText().equals("")){
            User1.setText("Ingrese el nombre de usuario");
            User1.setForeground(Color.gray);
        }
        if(!User1.getText().equals("Ingrese el nombre de usuario") && User1.getForeground() == Color.gray){
            User1.setForeground(Color.BLACK);
        }
        if(User1.getText().equals("Ingrese el nombre de usuario") && User1.getForeground() == Color.BLACK){
            User1.setForeground(Color.gray);
        }
        if(Password2.getText().equals("")){
            Password2Text.setText("Ingrese nuevamente su contraseña");
        }
        Password1Text.setText("");
        Password1.setForeground(Color.BLACK);
    }//GEN-LAST:event_Password1MousePressed

    private void Password1SeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password1SeeMousePressed
        if(ver[0] == false){
            Password1.setEchoChar((char) 0);
            Password1See.setIcon(new ImageIcon(getClass().getResource("/com/app/imagenes/Eye-removebg-preview.png")));
            ver[0] = true;
        }
        else{
            Password1.setEchoChar('\u2022');
            Password1See.setIcon(new ImageIcon(getClass().getResource("/com/app/imagenes/Noeye-removebg-preview.png")));
            ver[0] = false;
        }
    }//GEN-LAST:event_Password1SeeMousePressed

    private void Password2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password2MousePressed
        if(User1.getText().equals("")){
            User1.setText("Ingrese el nombre de usuario");
            User1.setForeground(Color.gray);
        }
        if(!User1.getText().equals("Ingrese el nombre de usuario") && User1.getForeground() == Color.gray){
            User1.setForeground(Color.BLACK);
        }
        if(User1.getText().equals("Ingrese el nombre de usuario") && User1.getForeground() == Color.BLACK){
            User1.setForeground(Color.gray);
        }
        if(Password1.getText().equals("")){
            Password1Text.setText("Ingrese su contraseña");
        }
        Password2Text.setText("");
        Password2.setForeground(Color.BLACK);
    }//GEN-LAST:event_Password2MousePressed

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    private void Password2SeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password2SeeMousePressed
        if(ver[1] == false){
            Password2.setEchoChar((char) 0);
            Password2See.setIcon(new ImageIcon(getClass().getResource("/com/app/imagenes/Eye-removebg-preview.png")));
            ver[1] = true;
        }
        else{
            Password2.setEchoChar('\u2022');
            Password2See.setIcon(new ImageIcon(getClass().getResource("/com/app/imagenes/Noeye-removebg-preview.png")));
            ver[1] = false;
        }
    }//GEN-LAST:event_Password2SeeMousePressed

    private void InicioSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioSesionMousePressed
        JFrame frame = this;
        Inicio_sesion is = new Inicio_sesion(grafo,cox,new Buffer());
        is.setVisible(true); 
        is.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Timer timer = new Timer(1, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                frame.setVisible(false);
            }
        });
        timer.start();
    }//GEN-LAST:event_InicioSesionMousePressed
    private void carrusel(){
        
        
        ImageIcon[] imagenes = new ImageIcon[]{
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG1.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG2.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG3.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG4.jpg"))
        };
        Carrusel.setIcon(imagenes[0]);
        Timer timer = new Timer(2000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                indice = (indice + 1) % imagenes.length;
                Carrusel.setIcon(imagenes[indice]);
            }
        });
        timer.start();
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carrusel;
    private javax.swing.JPanel CrearCuenta;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JLabel IniciarSesionTexto1;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JLabel Password1See;
    private javax.swing.JLabel Password1Text;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JLabel Password2See;
    private javax.swing.JLabel Password2Text;
    private javax.swing.JPanel SeparadorPass;
    private javax.swing.JPanel SeparadorPass4;
    private javax.swing.JPanel SeparadorUser;
    private javax.swing.JTextField User1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}