/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import com.app.conexion.Conexion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import com.app.conexion.data.Sesion;

/**
 *
 * @author bohor
 */
public class crear_cuenta extends javax.swing.JFrame {
    
    int indice = 0;
    
    private static final Conexion cox = new Conexion();

    /**
     * Creates new form Inicio_sesion
     */
    public crear_cuenta() {
        initComponents();
        carrusel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Fondo1 = new javax.swing.JPanel();
        User1 = new javax.swing.JTextField();
        Password2 = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Logo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        IniciarSesionTexto1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LogoN4 = new javax.swing.JLabel();
        SeparadorUser = new javax.swing.JPanel();
        SeparadorPass4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SeparadorPass = new javax.swing.JPanel();
        SeparadorPass2 = new javax.swing.JPanel();
        SeparadorPass3 = new javax.swing.JPanel();
        Password3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Mensaje = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JPanel();
        Carrusel = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("crear_cuenta.jMenu1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 60, 67));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo1.setBackground(new java.awt.Color(255, 190, 15));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User1.setBackground(new java.awt.Color(255, 190, 15));
        User1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        User1.setForeground(java.awt.Color.gray);
        User1.setText(bundle.getString("crear_cuenta.User1.text")); // NOI18N
        User1.setToolTipText(bundle.getString("crear_cuenta.User1.toolTipText")); // NOI18N
        User1.setBorder(null);
        User1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User1MousePressed(evt);
            }
        });
        Fondo1.add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 500, 30));

        Password2.setBackground(new java.awt.Color(255, 190, 15));
        Password2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password2.setForeground(java.awt.Color.gray);
        Password2.setText(bundle.getString("crear_cuenta.Password2.text")); // NOI18N
        Password2.setToolTipText(bundle.getString("crear_cuenta.Password2.toolTipText")); // NOI18N
        Password2.setActionCommand(bundle.getString("crear_cuenta.Password2.actionCommand")); // NOI18N
        Password2.setBorder(null);
        Password2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password2MousePressed(evt);
            }
        });
        Fondo1.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 500, 30));

        Password.setBackground(new java.awt.Color(255, 190, 15));
        Password.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password.setForeground(java.awt.Color.gray);
        Password.setText(bundle.getString("crear_cuenta.Password.text")); // NOI18N
        Password.setToolTipText(bundle.getString("crear_cuenta.Password.toolTipText")); // NOI18N
        Password.setActionCommand(bundle.getString("crear_cuenta.Password.actionCommand")); // NOI18N
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Fondo1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 500, 30));
        Password.getAccessibleContext().setAccessibleName(bundle.getString("crear_cuenta.Password.AccessibleContext.accessibleName")); // NOI18N

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        Fondo1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel3.setText(bundle.getString("crear_cuenta.jLabel3.text")); // NOI18N
        Fondo1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN3.setText(bundle.getString("crear_cuenta.LogoN3.text")); // NOI18N
        Fondo1.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 310, -1));

        IniciarSesionTexto1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 48)); // NOI18N
        IniciarSesionTexto1.setText(bundle.getString("crear_cuenta.IniciarSesionTexto1.text")); // NOI18N
        Fondo1.add(IniciarSesionTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 270, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel7.setText(bundle.getString("crear_cuenta.jLabel7.text")); // NOI18N
        Fondo1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN4.setText(bundle.getString("crear_cuenta.LogoN4.text")); // NOI18N
        Fondo1.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, -1));

        SeparadorUser.setBackground(new java.awt.Color(0, 0, 0));
        Fondo1.add(SeparadorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 500, 1));

        SeparadorPass4.setBackground(new java.awt.Color(0, 0, 0));
        Fondo1.add(SeparadorPass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 505, 1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel2.setText(bundle.getString("crear_cuenta.jLabel2.text")); // NOI18N
        Fondo1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        jPanel1.setBackground(new java.awt.Color(189, 32, 0));
        jPanel1.setForeground(new java.awt.Color(140, 0, 0));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(bundle.getString("crear_cuenta.jLabel1.text")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel4.setBackground(new java.awt.Color(189, 32, 0));
        jPanel4.setForeground(new java.awt.Color(140, 0, 0));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(jPanel4, new java.awt.GridBagConstraints());

        Fondo1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 750, 160, 70));

        SeparadorPass.setBackground(new java.awt.Color(0, 0, 0));

        SeparadorPass2.setBackground(new java.awt.Color(0, 0, 0));

        SeparadorPass3.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorPass2.add(SeparadorPass3);

        Password3.setBackground(new java.awt.Color(255, 190, 15));
        Password3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Password3.setForeground(java.awt.Color.gray);
        Password3.setText(bundle.getString("crear_cuenta.Password3.text")); // NOI18N
        Password3.setToolTipText(bundle.getString("crear_cuenta.Password3.toolTipText")); // NOI18N
        Password3.setActionCommand(bundle.getString("crear_cuenta.Password3.actionCommand")); // NOI18N
        Password3.setBorder(null);
        Password3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Password3MousePressed(evt);
            }
        });
        Password3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password3ActionPerformed(evt);
            }
        });
        SeparadorPass2.add(Password3);

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        jLabel8.setText(bundle.getString("crear_cuenta.jLabel8.text")); // NOI18N
        SeparadorPass2.add(jLabel8);

        SeparadorPass.add(SeparadorPass2);

        Fondo1.add(SeparadorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 500, 1));

        jPanel5.setBackground(new java.awt.Color(189, 32, 0));
        jPanel5.setForeground(new java.awt.Color(140, 0, 0));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(bundle.getString("crear_cuenta.jLabel6.text")); // NOI18N
        jPanel5.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel6.setBackground(new java.awt.Color(189, 32, 0));
        jPanel6.setForeground(new java.awt.Color(140, 0, 0));
        jPanel6.setLayout(new java.awt.GridBagLayout());
        jPanel5.add(jPanel6, new java.awt.GridBagConstraints());

        Fondo1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 160, 70));

        Mensaje.setForeground(new java.awt.Color(204, 255, 204));
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Mensaje.setText(bundle.getString("crear_cuenta.dwdawdad.text")); // NOI18N
        Mensaje.setName("dwdawdad"); // NOI18N
        Fondo1.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 830, 270, 20));
        Mensaje.getAccessibleContext().setAccessibleName(bundle.getString("crear_cuenta.dwdawdad.AccessibleContext.accessibleName")); // NOI18N

        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 1080));

        Fondo2.setBackground(new java.awt.Color(140, 0, 0));
        Fondo2.setForeground(new java.awt.Color(0, 60, 67));
        Fondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Fondo2.add(Carrusel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 830, 930));

        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        if(User1.getText().equals("")){
            User1.setText("Ingrese el nombre de usuario");
            User1.setForeground(Color.gray);
        }
        if(Password2.getText().equals("")){
            Password2.setText("Ingrese su contraseña");
            Password2.setForeground(Color.gray);
        }
        if(!Password.getText().equals("Ingrese nuevamente su contraseña")){
            return;
        }
        else{
            Password.setText("");
            Password.setForeground(Color.black);
        }

    }//GEN-LAST:event_PasswordMousePressed

    private void User1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User1MousePressed
        if(Password2.getText().equals("")){
                Password2.setText("Ingrese su contraseña");
                Password2.setForeground(Color.gray);
        }
        if(Password.getText().equals("")){
                Password.setText("Ingrese nuevamente su contraseña");
                Password.setForeground(Color.gray);
        }
        if(!User1.getText().equals("Ingrese el nombre de usuario")){
            return;
        }
        else{
            User1.setText("");
        User1.setForeground(Color.black);
        }
        

    }//GEN-LAST:event_User1MousePressed

    private void Password2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password2MousePressed
        if(Password.getText().equals("")){
                Password.setText("Ingrese nuevamente su contraseña");
                Password.setForeground(Color.gray);
        }
        if(User1.getText().equals("")){
                User1.setText("Ingrese su nombre de usuario");
                User1.setForeground(Color.gray);
        }
        if(!Password2.getText().equals("Ingrese su contraseña")){
            return;
        }
        
        
        Password2.setText("");
        Password2.setForeground(Color.black);
    }//GEN-LAST:event_Password2MousePressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void Password3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password3ActionPerformed

    private void Password3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password3MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        Inicio_sesion is = new Inicio_sesion();
        this.setVisible(false);
        is.setVisible(true);
        
        is.setExtendedState(is.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        if(!Password.getText().equals(Password2.getText())){
            Mensaje.setText("Contraseñas no coinciden");
            Mensaje.setForeground(Color.RED);
        }
        else{
            cox.addTotableUsers(User1.getText(), Password.getText(), Mensaje);
        }
    }//GEN-LAST:event_jPanel5MousePressed
    private void carrusel(){
        
        
        ImageIcon[] imagenes = new ImageIcon[]{
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG1.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG2.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG3.jpg")),
            new ImageIcon(getClass().getResource("/com/app/imagenes/IMG4.jpg"))
        };
        Carrusel.setIcon(imagenes[0]);
        Timer timer = new Timer(1750, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                indice = (indice + 1) % imagenes.length;
                Carrusel.setIcon(imagenes[indice]);
            }
        });
        timer.start();
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carrusel;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JLabel IniciarSesionTexto1;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Password2;
    private javax.swing.JTextField Password3;
    private javax.swing.JPanel SeparadorPass;
    private javax.swing.JPanel SeparadorPass2;
    private javax.swing.JPanel SeparadorPass3;
    private javax.swing.JPanel SeparadorPass4;
    private javax.swing.JPanel SeparadorUser;
    private javax.swing.JTextField User1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}