/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import Clases.PanelRound;
import com.app.conexion.Conexion;
import com.app.conexion.data.Sesion;
import com.app.manejodatos.Grafo;
import com.app.manejodatos.ListaEnlazada;
import com.app.manejodatos.Nodo;
import com.app.manejodatos.Stack;
import combo_suggestion.ComboBoxSuggestion;
import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;
import raven.toast.Notifications;

/**
 *
 * @author ADMIN
 */
public class EliminarNodo extends javax.swing.JFrame {

    Grafo grafo = null;
    Sesion sesion = null;
    Conexion cox = null;
    Boolean perm = false;
    Drawer draw = null;
    ListaEnlazada cargar = null;
    Stack Nodoseliminados = new Stack();

    /**
     * Creates new form EliminarNodo
     */
    
    public EliminarNodo(Sesion sesion, Conexion coxload, Grafo grafoload) {
        this.sesion = sesion;
        PanelRound dgree1 = new PanelRound();
        initComponents();
        Buscar4.setLayout(new BorderLayout());
        Buscar4.add(dgree1,BorderLayout.CENTER);
        Buscar4.setOpaque(true);
        cox = coxload;
        grafo = grafoload;
        cargar = grafo.getNodos();

        // Removed duplicate initComponents call
        draw = new Drawer(false, cox, null, grafo.getNodos(), grafo.getAristas());
        jPanel3.add(draw,BorderLayout.CENTER);
        jPanel3.setVisible(true);
        Bienvenida2.setText("¡Bienvenido(a) " + this.sesion.getNombre() + "!");
        Nodoeliminar.addItem("Biblioteca");
        Nodoeliminar.addItem("Auditorio menor");
        Nodoeliminar.addItem("Auditorio mayor");
        poblarComponentes();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Bienvenida2 = new javax.swing.JLabel();
        Nodoeliminar = new combo_suggestion.ComboBoxSuggestion();
        a = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar4.setBackground(new java.awt.Color(255, 255, 255));
        Buscar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarNodo(evt);
            }
        });
        Buscar4.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eliminar");
        Buscar4.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, 170, 70));

        Bienvenida2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida2.setForeground(new java.awt.Color(0, 0, 0));
        Bienvenida2.setText("¡Bienvenido(a)!");
        jPanel1.add(Bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        Nodoeliminar.setBackground(new java.awt.Color(0, 0, 0));
        Nodoeliminar.setBorder(null);
        Nodoeliminar.setMaximumRowCount(5);
        Nodoeliminar.setFocusCycleRoot(true);
        Nodoeliminar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(Nodoeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 220, 50));

        a.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        a.setText(bundle.getString("crear_cuenta.jLabel3.text")); // NOI18N
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/upblogo.jpg"))); // NOI18N
        jLabel9.setText(bundle.getString("Inicio_sesion.jLabel9.text")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 1080));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 830, 900));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 830, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarNodo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarNodo
        String Elim = (String) Nodoeliminar.getSelectedItem();
        Nodo nodoAEliminar = null;
        String nodoNombre = (String) Nodoeliminar.getSelectedItem();
        if (nodoNombre == null || nodoNombre.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.BOTTOM_LEFT,"Seleccione un nodo");
            return;
        }
        if(nodoNombre == "Auditorio mayor"){
            nodoAEliminar = cargar.obtenerNodo("H");
        }
        else if(nodoNombre == "Auditorio menor" || nodoNombre ==  "Biblioteca"){
            nodoAEliminar = cargar.obtenerNodo("J");
        }
        else{
            // aca se encuanta el nodo a remover
            nodoAEliminar = cargar.obtenerNodo(nodoNombre);
        }
        
        if (nodoAEliminar != null) {
            cargar.eliminarNodoBIEN(nodoAEliminar.getNombre());
            Notifications.getInstance().show(Notifications.Type.SUCCESS,Notifications.Location.BOTTOM_LEFT,"Nodo '" + nodoNombre + "' eliminado.");
            Nodoseliminados.push(nodoAEliminar);
           
            DefaultComboBoxModel<String> nueva = new DefaultComboBoxModel<>();
            for (Nodo nombreNodo : cargar) {
                nueva.addElement(nombreNodo.getNombre());
            }
            if(cargar.NodoPresente("J")){
                nueva.addElement("Biblioteca");
                nueva.addElement("Auditorio menor");
            }
            if(cargar.NodoPresente("H")){
                nueva.addElement("Auditorio mayor");
            }
            Nodoeliminar.setModel(nueva);
            draw.repaint();
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.BOTTOM_LEFT,"Nodo "+ nodoNombre +" no encontrado");
        }
    }//GEN-LAST:event_EliminarNodo
      private void poblarComponentes() {
        Nodo temp = cargar.getCabeza();
        while (temp != null) {
            Nodoeliminar.addItem(temp.getNombre());
            temp = temp.getSiguiente();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida2;
    private javax.swing.JPanel Buscar4;
    private combo_suggestion.ComboBoxSuggestion Nodoeliminar;
    private javax.swing.JLabel a;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
