/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import com.app.conexion.Conexion;
import com.app.conexion.data.Sesion;
import com.app.manejodatos.Grafo;
import com.app.manejodatos.ListaEnlazada;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class EliminarArista extends javax.swing.JFrame {

    Grafo grafo = null;
    boolean check = true;
    Sesion sesion = null;
    Conexion cox = null;
    Boolean perm = false;
    Drawer draw = null;
    ListaEnlazada cargar = null;

    /**
     * Creates new form EliminarArista
     */
    public EliminarArista() {
        initComponents();
        cox = coxload;

        grafo = grafoload;
        cargar = grafo.getNodos();
        this.perm = perm;
        initComponents();
        draw = new Drawer(perm, cox, null, grafo.getNodos(), grafo.getAristas());
        this.sesion = sesion;
        Bienvenida.setText("¡Bienvenido(a) " + sesion.getNombre() + "!");
        NodoI.addItem("Biblioteca");
        NodoI.addItem("Auditorio menor");
        NodoI.addItem("Auditorio mayor");
        NodoF.addItem("Biblioteca");
        NodoF.addItem("Auditorio menor");
        NodoF.addItem("Auditorio mayor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        LogoN4 = new javax.swing.JLabel();
        dndva2 = new javax.swing.JLabel();
        NodoF = new combo_suggestion.ComboBoxSuggestion();
        NodoI = new combo_suggestion.ComboBoxSuggestion();
        Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dndviene2 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 190, 15));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        jPanel3.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        LogoN3.setText(bundle.getString("Inicio_sesion.LogoN3.text")); // NOI18N
        jPanel3.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, 80));

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN4.setText(bundle.getString("Inicio_sesion.LogoN4.text")); // NOI18N
        jPanel3.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 610, 90));

        dndva2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        dndva2.setText("Edificio final");
        jPanel3.add(dndva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 190, 40));

        NodoF.setBackground(new java.awt.Color(140, 0, 0));
        NodoF.setBorder(null);
        NodoF.setMaximumRowCount(5);
        NodoF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NodoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NodoFActionPerformed(evt);
            }
        });
        jPanel3.add(NodoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 220, 50));

        NodoI.setBackground(new java.awt.Color(140, 0, 0));
        NodoI.setBorder(null);
        NodoI.setMaximumRowCount(5);
        NodoI.setFocusCycleRoot(true);
        NodoI.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel3.add(NodoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 220, 50));

        Buscar.setBackground(new java.awt.Color(140, 0, 0));
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");
        Buscar.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(140, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Buscar.add(jPanel2, new java.awt.GridBagConstraints());

        jPanel3.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 170, 70));

        dndviene2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        dndviene2.setText("Edificio Inicial ");
        jPanel3.add(dndviene2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 230, 40));

        CerrarSesion.setBackground(new java.awt.Color(140, 0, 0));
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarSesionMousePressed(evt);
            }
        });
        CerrarSesion.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cerrar Sesion");
        CerrarSesion.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel3.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 980, 170, 70));

        Bienvenida.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida.setText("¡Bienvenido(a)!");
        jPanel3.add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 1080));

        jPanel4.setBackground(new java.awt.Color(140, 0, 0));
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, -20, 1350, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NodoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NodoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NodoFActionPerformed

    private void CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMousePressed
        sesion = null;
        JFrame frame = this;
        Inicio_sesion inis = new Inicio_sesion(grafo);
        inis.setExtendedState(JFrame.MAXIMIZED_BOTH);
        inis.setVisible(true);
        Timer timer = new Timer(10, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                frame.setVisible(false);
            }
        });
        timer.start();
    }//GEN-LAST:event_CerrarSesionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarArista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarArista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarArista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarArista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarArista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JPanel Buscar;
    private javax.swing.JPanel CerrarSesion;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private combo_suggestion.ComboBoxSuggestion NodoF;
    private combo_suggestion.ComboBoxSuggestion NodoI;
    private javax.swing.JLabel dndva2;
    private javax.swing.JLabel dndviene2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
