/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

import com.app.conexion.Conexion;
import com.app.conexion.data.Sesion;
import com.app.manejodatos.Grafo;
import com.app.manejodatos.ListaEnlazadaNodos;
import com.app.manejodatos.Nodo;
import com.app.utilidad.PanelRound;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class EliminarArista extends javax.swing.JFrame {

    Grafo grafo = null;
    boolean check = true;
    Sesion sesion = null;
    Conexion cox = null;
    Boolean perm = false;
    Drawer draw = null;
    ListaEnlazadaNodos cargar = null;
    Buffer buffer;

    /**
     * Creates new form EliminarArista
     */
   

    public EliminarArista(Sesion sesion, Conexion coxload, Grafo grafoload, Boolean perm,Buffer buf,Drawer draw) {
        initComponents();
        buffer = buf;
        this.draw = draw;
        cox = coxload;
        grafo = grafoload;
        cargar = grafo.getNodos();
        this.perm = perm;
        // Removed duplicate initComponents call
        this.sesion = sesion;
        PanelRound dgree1 = new PanelRound();
        PanelRound dgree2 = new PanelRound();
        
        Buscar.setLayout(new BorderLayout());
        Buscar.add(dgree1,BorderLayout.CENTER);
        Buscar.setVisible(true);
        
        CerrarSesion.setLayout(new BorderLayout());
        CerrarSesion.add(dgree2,BorderLayout.CENTER);
        CerrarSesion.setVisible(true);
        
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(draw, BorderLayout.CENTER);
        jPanel5.setVisible(true);
        Bienvenida.setText("¡Bienvenido(a) " + sesion.getNombre() + "!");
         if (draw.getNodos().NodoPresente("J")) {
            NodoI.addItem("Biblioteca");
            NodoI.addItem("Auditorio menor");
            NodoF.addItem("Auditorio menor");
            NodoF.addItem("Biblioteca");
        }
        if (draw.getNodos().NodoPresente("H")) {
            NodoI.addItem("Auditorio mayor");
            NodoF.addItem("Auditorio mayor");
        }
        poblarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dndva2 = new javax.swing.JLabel();
        NodoF = new combo_suggestion.ComboBoxSuggestion();
        NodoI = new combo_suggestion.ComboBoxSuggestion();
        dndviene2 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bienvenida = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Eliminar(evt);
            }
        });
        Buscar.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");
        Buscar.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(140, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Buscar.add(jPanel2, new java.awt.GridBagConstraints());

        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 170, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dndva2.setBackground(new java.awt.Color(0, 0, 0));
        dndva2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        dndva2.setForeground(new java.awt.Color(0, 0, 0));
        dndva2.setText("Edificio final");
        jPanel3.add(dndva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 190, 40));

        NodoF.setBackground(new java.awt.Color(0, 0, 0));
        NodoF.setBorder(null);
        NodoF.setMaximumRowCount(5);
        NodoF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NodoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NodoFActionPerformed(evt);
            }
        });
        jPanel3.add(NodoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 220, 50));

        NodoI.setBackground(new java.awt.Color(0, 0, 0));
        NodoI.setBorder(null);
        NodoI.setMaximumRowCount(5);
        NodoI.setFocusCycleRoot(true);
        NodoI.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel3.add(NodoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 220, 50));

        dndviene2.setBackground(new java.awt.Color(0, 0, 0));
        dndviene2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 36)); // NOI18N
        dndviene2.setForeground(new java.awt.Color(0, 0, 0));
        dndviene2.setText("Edificio Inicial ");
        jPanel3.add(dndviene2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 230, 40));

        CerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarSesionMousePressed(evt);
            }
        });
        CerrarSesion.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Volver");
        CerrarSesion.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel3.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1000, 170, 70));

        Bienvenida.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenida.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        Bienvenida.setText("¡Bienvenido(a)!");
        jPanel3.add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/upblogo.jpg"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        jLabel9.setText(bundle.getString("Inicio_sesion.jLabel9.text")); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 220));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 1080));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 830, 900));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 830, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NodoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NodoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NodoFActionPerformed

    private void CerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMousePressed

        JFrame frame = this;
        ADMIN inis = new ADMIN(grafo,cox,sesion,buffer,draw);
        inis.setExtendedState(JFrame.MAXIMIZED_BOTH);
        inis.setVisible(true);
        Timer timer = new Timer(10, new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                frame.setVisible(false);
            }
        });
        timer.start();
    }//GEN-LAST:event_CerrarSesionMousePressed

    private void Eliminar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar
        String ini = (String) NodoI.getSelectedItem();
        String fin = (String) NodoF.getSelectedItem();
        if(ini.equals("Biblioteca") || ini.equals("Auditorio menor")){
            ini = "J";
        }
        if(fin.equals("Biblioteca") || fin.equals("Auditorio menor")){
            fin = "J";
        }
        if(ini.equals("Auditorio mayor")){
            ini = "H";
        }
        if(fin.equals("Auditorio mayor")){
            ini = "H";
        }
        draw.eliminarArista1(ini, fin,buffer);
        draw.reiniciar();
    }//GEN-LAST:event_Eliminar
      private void poblarComponentes() {         
        for(Nodo temp: cargar){
            NodoI.addItem(temp.getNombre());
            NodoF.addItem(temp.getNombre());
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JPanel Buscar;
    private javax.swing.JPanel CerrarSesion;
    private combo_suggestion.ComboBoxSuggestion NodoF;
    private combo_suggestion.ComboBoxSuggestion NodoI;
    private javax.swing.JLabel dndva2;
    private javax.swing.JLabel dndviene2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
