/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;


import com.app.conexion.Conexion;
import com.app.conexion.data.Sesion;
import com.app.manejodatos.Grafo;
import com.app.manejodatos.ListaEnlazada;
import com.app.manejodatos.Nodo;

/**
 *
 * @author ADMIN
 */
public class EliminarNodo extends javax.swing.JFrame {
    
    Grafo grafo = null;
    boolean check = true;
    Sesion sesion = null;
    Conexion cox = null;
    Boolean perm = false;
    Drawer draw = null;
    ListaEnlazada cargar = null;
    /**
     * Creates new form EliminarNodo
     */
    public EliminarNodo(Sesion sesion,Conexion coxload,Grafo grafoload,Boolean perm) {
        initComponents();
        cox = coxload;
        
        grafo = grafoload;
        cargar = grafo.getNodos();
        this.perm = perm;
        initComponents();
        draw = new Drawer(perm,cox,null,grafo.getNodos(),grafo.getAristas());
         this.sesion = sesion;
        Bienvenida2.setText("¡Bienvenido(a) " + sesion.getNombre() + "!");
        Nodoeliminar.addItem("Biblioteca");
        Nodoeliminar.addItem("Auditorio menor");
        Nodoeliminar.addItem("Auditorio mayor");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoN4 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        LogoN3 = new javax.swing.JLabel();
        Buscar4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Bienvenida2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nodoeliminar = new combo_suggestion.ComboBoxSuggestion();
        a = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 190, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoN4.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/app/interfaz/Bundle"); // NOI18N
        LogoN4.setText(bundle.getString("crear_cuenta.LogoN4.text")); // NOI18N
        jPanel1.add(LogoN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 660, 90));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/imagenes/imagen_2025-04-13_002438034 (1).png"))); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        LogoN3.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        LogoN3.setText(bundle.getString("Inicio_sesion.LogoN3.text")); // NOI18N
        jPanel1.add(LogoN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 340, 80));

        Buscar4.setBackground(new java.awt.Color(140, 0, 0));
        Buscar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Buscar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarNodo(evt);
            }
        });
        Buscar4.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eliminar");
        Buscar4.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel1.add(Buscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, 170, 70));

        Bienvenida2.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 48)); // NOI18N
        Bienvenida2.setText("¡Bienvenido(a)!");
        jPanel1.add(Bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(140, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -20, 150, 870));

        Nodoeliminar.setBackground(new java.awt.Color(140, 0, 0));
        Nodoeliminar.setBorder(null);
        Nodoeliminar.setMaximumRowCount(5);
        Nodoeliminar.setFocusCycleRoot(true);
        Nodoeliminar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(Nodoeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 220, 50));

        a.setFont(new java.awt.Font("Roboto Condensed", 0, 36)); // NOI18N
        a.setText(bundle.getString("crear_cuenta.jLabel3.text")); // NOI18N
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarNodo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarNodo
        Object Elim = Nodoeliminar.getSelectedItem();
        Elim = null;
    }//GEN-LAST:event_EliminarNodo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarNodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida2;
    private javax.swing.JPanel Buscar4;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoN3;
    private javax.swing.JLabel LogoN4;
    private combo_suggestion.ComboBoxSuggestion Nodoeliminar;
    private javax.swing.JLabel a;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
