/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

/**
 *
 * @author bohor
 */
public class TEMP extends javax.swing.JFrame {

    /**
     * Creates new form TEMP
     */
    public TEMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EdE = new javax.swing.JButton();
        EdF = new javax.swing.JButton();
        EdG = new javax.swing.JButton();
        EdH = new javax.swing.JButton();
        EdI = new javax.swing.JButton();
        EdL = new javax.swing.JButton();
        Edk = new javax.swing.JButton();
        EdD = new javax.swing.JButton();
        EdJ = new javax.swing.JButton();
        EdC = new javax.swing.JButton();
        EdB = new javax.swing.JButton();
        EdA = new javax.swing.JButton();
        EdA1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EdE.setBackground(new java.awt.Color(191, 28, 9));
        EdE.setForeground(new java.awt.Color(255, 255, 255));
        EdE.setText("E");
        EdE.setBorder(null);
        EdE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdEActionPerformed(evt);
            }
        });

        EdF.setBackground(new java.awt.Color(191, 28, 9));
        EdF.setForeground(new java.awt.Color(255, 255, 255));
        EdF.setText("F");
        EdF.setBorder(null);
        EdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdFActionPerformed(evt);
            }
        });

        EdG.setBackground(new java.awt.Color(191, 28, 9));
        EdG.setForeground(new java.awt.Color(255, 255, 255));
        EdG.setText("G");
        EdG.setBorder(null);
        EdG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdGActionPerformed(evt);
            }
        });

        EdH.setBackground(new java.awt.Color(191, 28, 9));
        EdH.setForeground(new java.awt.Color(255, 255, 255));
        EdH.setText("H");
        EdH.setBorder(null);
        EdH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdHActionPerformed(evt);
            }
        });

        EdI.setBackground(new java.awt.Color(11, 50, 93));
        EdI.setForeground(new java.awt.Color(255, 255, 255));
        EdI.setText("I");
        EdI.setBorder(null);
        EdI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdIActionPerformed(evt);
            }
        });

        EdL.setBackground(new java.awt.Color(103, 140, 62));
        EdL.setForeground(new java.awt.Color(255, 255, 255));
        EdL.setText("L");
        EdL.setBorder(null);
        EdL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdLActionPerformed(evt);
            }
        });

        Edk.setBackground(new java.awt.Color(216, 120, 34));
        Edk.setForeground(new java.awt.Color(255, 255, 255));
        Edk.setText("K");
        Edk.setBorder(null);
        Edk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdkActionPerformed(evt);
            }
        });

        EdD.setBackground(new java.awt.Color(241, 177, 53));
        EdD.setForeground(new java.awt.Color(255, 255, 255));
        EdD.setText("D");
        EdD.setBorder(null);
        EdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdDActionPerformed(evt);
            }
        });

        EdJ.setBackground(new java.awt.Color(157, 204, 212));
        EdJ.setText("J");
        EdJ.setBorder(null);
        EdJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdJActionPerformed(evt);
            }
        });

        EdC.setBackground(new java.awt.Color(241, 177, 53));
        EdC.setForeground(new java.awt.Color(255, 255, 255));
        EdC.setText("C");
        EdC.setBorder(null);
        EdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdCActionPerformed(evt);
            }
        });

        EdB.setBackground(new java.awt.Color(241, 177, 53));
        EdB.setForeground(new java.awt.Color(255, 255, 255));
        EdB.setText("B");
        EdB.setBorder(null);
        EdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdBActionPerformed(evt);
            }
        });

        EdA.setBackground(new java.awt.Color(241, 177, 53));
        EdA.setForeground(new java.awt.Color(255, 255, 255));
        EdA.setText("A");
        EdA.setBorder(null);
        EdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdAActionPerformed(evt);
            }
        });

        EdA1.setBackground(new java.awt.Color(113, 49, 133));
        EdA1.setForeground(new java.awt.Color(255, 255, 255));
        EdA1.setText("TEMPLO");
        EdA1.setBorder(null);
        EdA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(Edk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(EdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(530, 530, 530)
                            .addComponent(EdI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(460, 460, 460)
                            .addComponent(EdE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(EdH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(EdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(EdG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EdA1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(EdA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(EdB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Edk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(EdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(EdI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(EdB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(EdJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdEActionPerformed

    private void EdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdFActionPerformed

    private void EdGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdGActionPerformed

    private void EdHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdHActionPerformed

    private void EdIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdIActionPerformed

    private void EdLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdLActionPerformed

    private void EdkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdkActionPerformed

    private void EdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdDActionPerformed

    private void EdJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdJActionPerformed

    private void EdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdCActionPerformed

    private void EdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdBActionPerformed

    private void EdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdAActionPerformed

    private void EdA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EdA;
    private javax.swing.JButton EdA1;
    private javax.swing.JButton EdB;
    private javax.swing.JButton EdC;
    private javax.swing.JButton EdD;
    private javax.swing.JButton EdE;
    private javax.swing.JButton EdF;
    private javax.swing.JButton EdG;
    private javax.swing.JButton EdH;
    private javax.swing.JButton EdI;
    private javax.swing.JButton EdJ;
    private javax.swing.JButton EdL;
    private javax.swing.JButton Edk;
    // End of variables declaration//GEN-END:variables
}
