/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.interfaz;

/**
 *
 * @author bohor
 */
public class TEMP extends javax.swing.JFrame {

    /**
     * Creates new form TEMP
     */
    public TEMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        EdE1 = new javax.swing.JButton();
        EdF1 = new javax.swing.JButton();
        EdG1 = new javax.swing.JButton();
        EdH1 = new javax.swing.JButton();
        EdI1 = new javax.swing.JButton();
        EdL1 = new javax.swing.JButton();
        Edk1 = new javax.swing.JButton();
        EdD1 = new javax.swing.JButton();
        EdJ1 = new javax.swing.JButton();
        EdC1 = new javax.swing.JButton();
        EdB1 = new javax.swing.JButton();
        EdA2 = new javax.swing.JButton();
        EdA3 = new javax.swing.JButton();
        EdE = new javax.swing.JButton();
        EdF = new javax.swing.JButton();
        EdG = new javax.swing.JButton();
        EdH = new javax.swing.JButton();
        EdI = new javax.swing.JButton();
        EdL = new javax.swing.JButton();
        Edk = new javax.swing.JButton();
        EdD = new javax.swing.JButton();
        EdJ = new javax.swing.JButton();
        EdC = new javax.swing.JButton();
        EdB = new javax.swing.JButton();
        EdA = new javax.swing.JButton();
        EdA1 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EdE1.setBackground(new java.awt.Color(191, 28, 9));
        EdE1.setForeground(new java.awt.Color(255, 255, 255));
        EdE1.setText("E");
        EdE1.setBorder(null);
        EdE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdE1ActionPerformed(evt);
            }
        });

        EdF1.setBackground(new java.awt.Color(191, 28, 9));
        EdF1.setForeground(new java.awt.Color(255, 255, 255));
        EdF1.setText("F");
        EdF1.setBorder(null);
        EdF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdF1ActionPerformed(evt);
            }
        });

        EdG1.setBackground(new java.awt.Color(191, 28, 9));
        EdG1.setForeground(new java.awt.Color(255, 255, 255));
        EdG1.setText("G");
        EdG1.setBorder(null);
        EdG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdG1ActionPerformed(evt);
            }
        });

        EdH1.setBackground(new java.awt.Color(191, 28, 9));
        EdH1.setForeground(new java.awt.Color(255, 255, 255));
        EdH1.setText("H");
        EdH1.setBorder(null);
        EdH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdH1ActionPerformed(evt);
            }
        });

        EdI1.setBackground(new java.awt.Color(11, 50, 93));
        EdI1.setForeground(new java.awt.Color(255, 255, 255));
        EdI1.setText("I");
        EdI1.setBorder(null);
        EdI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdI1ActionPerformed(evt);
            }
        });

        EdL1.setBackground(new java.awt.Color(103, 140, 62));
        EdL1.setForeground(new java.awt.Color(255, 255, 255));
        EdL1.setText("L");
        EdL1.setBorder(null);
        EdL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdL1ActionPerformed(evt);
            }
        });

        Edk1.setBackground(new java.awt.Color(216, 120, 34));
        Edk1.setForeground(new java.awt.Color(255, 255, 255));
        Edk1.setText("K");
        Edk1.setBorder(null);
        Edk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edk1ActionPerformed(evt);
            }
        });

        EdD1.setBackground(new java.awt.Color(241, 177, 53));
        EdD1.setForeground(new java.awt.Color(255, 255, 255));
        EdD1.setText("D");
        EdD1.setBorder(null);
        EdD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdD1ActionPerformed(evt);
            }
        });

        EdJ1.setBackground(new java.awt.Color(157, 204, 212));
        EdJ1.setText("J");
        EdJ1.setBorder(null);
        EdJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdJ1ActionPerformed(evt);
            }
        });

        EdC1.setBackground(new java.awt.Color(241, 177, 53));
        EdC1.setForeground(new java.awt.Color(255, 255, 255));
        EdC1.setText("C");
        EdC1.setBorder(null);
        EdC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdC1ActionPerformed(evt);
            }
        });

        EdB1.setBackground(new java.awt.Color(241, 177, 53));
        EdB1.setForeground(new java.awt.Color(255, 255, 255));
        EdB1.setText("B");
        EdB1.setBorder(null);
        EdB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdB1ActionPerformed(evt);
            }
        });

        EdA2.setBackground(new java.awt.Color(241, 177, 53));
        EdA2.setForeground(new java.awt.Color(255, 255, 255));
        EdA2.setText("A");
        EdA2.setBorder(null);
        EdA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdA2ActionPerformed(evt);
            }
        });

        EdA3.setBackground(new java.awt.Color(113, 49, 133));
        EdA3.setForeground(new java.awt.Color(255, 255, 255));
        EdA3.setText("TEMPLO");
        EdA3.setBorder(null);
        EdA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdA3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(Edk1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(EdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(530, 530, 530)
                            .addComponent(EdI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(460, 460, 460)
                            .addComponent(EdE1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(EdH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(EdD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(EdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(EdG1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addComponent(EdA3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(EdA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(EdB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Edk1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(EdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(EdI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdE1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdG1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdA3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(EdB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(EdJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EdE.setBackground(new java.awt.Color(191, 28, 9));
        EdE.setForeground(new java.awt.Color(255, 255, 255));
        EdE.setText("E");
        EdE.setBorder(null);
        EdE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdEActionPerformed(evt);
            }
        });

        EdF.setBackground(new java.awt.Color(191, 28, 9));
        EdF.setForeground(new java.awt.Color(255, 255, 255));
        EdF.setText("F");
        EdF.setBorder(null);
        EdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdFActionPerformed(evt);
            }
        });

        EdG.setBackground(new java.awt.Color(191, 28, 9));
        EdG.setForeground(new java.awt.Color(255, 255, 255));
        EdG.setText("G");
        EdG.setBorder(null);
        EdG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdGActionPerformed(evt);
            }
        });

        EdH.setBackground(new java.awt.Color(191, 28, 9));
        EdH.setForeground(new java.awt.Color(255, 255, 255));
        EdH.setText("H");
        EdH.setBorder(null);
        EdH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdHActionPerformed(evt);
            }
        });

        EdI.setBackground(new java.awt.Color(11, 50, 93));
        EdI.setForeground(new java.awt.Color(255, 255, 255));
        EdI.setText("I");
        EdI.setBorder(null);
        EdI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdIActionPerformed(evt);
            }
        });

        EdL.setBackground(new java.awt.Color(103, 140, 62));
        EdL.setForeground(new java.awt.Color(255, 255, 255));
        EdL.setText("L");
        EdL.setBorder(null);
        EdL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdLActionPerformed(evt);
            }
        });

        Edk.setBackground(new java.awt.Color(216, 120, 34));
        Edk.setForeground(new java.awt.Color(255, 255, 255));
        Edk.setText("K");
        Edk.setBorder(null);
        Edk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdkActionPerformed(evt);
            }
        });

        EdD.setBackground(new java.awt.Color(241, 177, 53));
        EdD.setForeground(new java.awt.Color(255, 255, 255));
        EdD.setText("D");
        EdD.setBorder(null);
        EdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdDActionPerformed(evt);
            }
        });

        EdJ.setBackground(new java.awt.Color(157, 204, 212));
        EdJ.setText("J");
        EdJ.setBorder(null);
        EdJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdJActionPerformed(evt);
            }
        });

        EdC.setBackground(new java.awt.Color(241, 177, 53));
        EdC.setForeground(new java.awt.Color(255, 255, 255));
        EdC.setText("C");
        EdC.setBorder(null);
        EdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdCActionPerformed(evt);
            }
        });

        EdB.setBackground(new java.awt.Color(241, 177, 53));
        EdB.setForeground(new java.awt.Color(255, 255, 255));
        EdB.setText("B");
        EdB.setBorder(null);
        EdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdBActionPerformed(evt);
            }
        });

        EdA.setBackground(new java.awt.Color(241, 177, 53));
        EdA.setForeground(new java.awt.Color(255, 255, 255));
        EdA.setText("A");
        EdA.setBorder(null);
        EdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdAActionPerformed(evt);
            }
        });

        EdA1.setBackground(new java.awt.Color(113, 49, 133));
        EdA1.setForeground(new java.awt.Color(255, 255, 255));
        EdA1.setText("TEMPLO");
        EdA1.setBorder(null);
        EdA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(Edk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(EdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(530, 530, 530)
                            .addComponent(EdI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(460, 460, 460)
                            .addComponent(EdE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(EdH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(EdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(EdG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EdA1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(EdA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(EdB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(EdJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Edk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(EdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(EdI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EdA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EdA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(EdB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(EdC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(EdJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdEActionPerformed

    private void EdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdFActionPerformed

    private void EdGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdGActionPerformed

    private void EdHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdHActionPerformed

    private void EdIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdIActionPerformed

    private void EdLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdLActionPerformed

    private void EdkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdkActionPerformed

    private void EdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdDActionPerformed

    private void EdJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdJActionPerformed

    private void EdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdCActionPerformed

    private void EdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdBActionPerformed

    private void EdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdAActionPerformed

    private void EdA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdA1ActionPerformed

    private void EdE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdE1ActionPerformed

    private void EdF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdF1ActionPerformed

    private void EdG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdG1ActionPerformed

    private void EdH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdH1ActionPerformed

    private void EdI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdI1ActionPerformed

    private void EdL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdL1ActionPerformed

    private void Edk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edk1ActionPerformed

    private void EdD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdD1ActionPerformed

    private void EdJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdJ1ActionPerformed

    private void EdC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdC1ActionPerformed

    private void EdB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdB1ActionPerformed

    private void EdA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdA2ActionPerformed

    private void EdA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdA3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EdA;
    private javax.swing.JButton EdA1;
    private javax.swing.JButton EdA2;
    private javax.swing.JButton EdA3;
    private javax.swing.JButton EdB;
    private javax.swing.JButton EdB1;
    private javax.swing.JButton EdC;
    private javax.swing.JButton EdC1;
    private javax.swing.JButton EdD;
    private javax.swing.JButton EdD1;
    private javax.swing.JButton EdE;
    private javax.swing.JButton EdE1;
    private javax.swing.JButton EdF;
    private javax.swing.JButton EdF1;
    private javax.swing.JButton EdG;
    private javax.swing.JButton EdG1;
    private javax.swing.JButton EdH;
    private javax.swing.JButton EdH1;
    private javax.swing.JButton EdI;
    private javax.swing.JButton EdI1;
    private javax.swing.JButton EdJ;
    private javax.swing.JButton EdJ1;
    private javax.swing.JButton EdL;
    private javax.swing.JButton EdL1;
    private javax.swing.JButton Edk;
    private javax.swing.JButton Edk1;
    private javax.swing.JFrame jFrame1;
    // End of variables declaration//GEN-END:variables
}
